[settings]
name = newbium

[display]
accounting = false
debug = false
logs = false
trace = false
single = false
json = true

[fields]
hide=
#show=CLogEntry:data,topics

[formats]
txrans_fmt = [{TIMESTAMP}]\t[{BLOCKNUMBER}]\t[{TRANSACTIONINDEX}]\t[{FROM}]\t[{TO}]\t[{VALUE}]\t[{GAS}]\t[{GASPRICE}]\t[{GASUSED}]\t[{ISERROR}]\t[{ENCODING}]\t[{ARTICULATEDTX}]

[[watches]]
list = [
    { address = "0x814964b1bceAf24e26296D031EaDf134a2Ca4105", name = "Newbium", firstBlock = 3989717, color = "green_c" },
    { address = "0xc9D7fEC9889690bBff0A0Df758D13e5A55dd7822", name = "Newbium Creator", firstBlock = 3984610, color = "green_c", enabled = false }
]
named = [
    { address = "0x8d12a197cb00d4747a1fe03395095ce2a5cc6819", name = "EtherDelta_2", color = "blue_b" }
]

# make sure to always put arrays at the end of the file
