[settings]
name = newbium

[display]
accounting = false
debug = false
logs = false
trace = false
single = false
json = true

[fields]
hide=
sxhow=CParameter:type

[formats]
trans_fmt = [{BLOCKNUMBER}]\t[{TRANSACTIONINDEX}]\t[{HASH}]
txrans_fmt = [{TIMESTAMP}]\t[{BLOCKNUMBER}]\t[{TRANSACTIONINDEX}]\t[{FROM}]\t[{TO}]\t[{VALUE}]\t[{GAS}]\t[{GASPRICE}]\t[{GASUSED}]\t[{ISERROR}]\t[{ENCODING}]\t[{ARTICULATEDTX}]

[[watches]]
list = [
    { address = "0x814964b1bceaf24e26296d031eadf134a2ca4105", name = "Newbium",         firstBlock = 3989717, color = "green_c" },
    { address = "0xc9d7fec9889690bbff0a0df758d13e5a55dd7822", name = "Newbium Creator", firstBlock = 3984610, color = "green_c" },
]
named = [
    { address = "0x8d12a197cb00d4747a1fe03395095ce2a5cc6819", name = "EtherDelta_2", color = "blue_b" },
    { address = "0x12459C951127e0c374FF9105DdA097662A027093", name = "0xProto_Exch1", color = "blue_b" },
]

# make sure to always put arrays at the end of the file
